packages:
  - apps/**
  - packages/**

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19
    '@types/react-dom': ^19
  types:
    typescript: ^5.8.3
    '@types/node': ^20
  build:
    rimraf: ^6.0.1
    tsup: ^8.4.0
  cli:
    inquirer: ^12.5.2
    turbo: ^2.5.0
  lint:
    '@biomejs/biome': ^1.9.4
  dev:
    '@ladle/react': ^5.0.2
  animation:
    gsap: ^3.12.7
    '@gsap/react': ^2.1.2
  css:
    lightningcss: ^1.30.1
  utils:
    'es-toolkit': ^1.36.0
    rxjs: ^7.8.2
    usehooks-ts: ^3.1.1