packages:
  - apps/**
  - packages/**

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19
    '@types/react-dom': ^19
  types:
    typescript: ^5.8.3
    '@types/node': ^20
  build:
    rimraf: ^6.0.1
    tsup: ^8.4.0
  cli:
    inquirer: ^12.5.2
    turbo: ^2.5.0
  lint:
    '@biomejs/biome': ^1.9.4
  dev:
    '@storybook/addon-a11y': ^10.5.10
    '@storybook/react-vite': ^10.5.10
    esbuild: ^0.28.2
    storybook: ^10.5.10
    vite: ^8.2.2
  animation:
    gsap: ^3.15.0
    '@gsap/react': ^2.1.2
    motion: ^13.1.1
  effect:
    effect: ^4.0.0-rc.112
  icons:
    lucide-react: ^1.39.0
  state:
    jotai: ^2.20.3
  css:
    lightningcss: ^1.30.1
    tailwindcss: ^4.1.7
    '@tailwindcss/postcss': ^4.1.7
  utils:
    clsx: ^2.1.1
    'es-toolkit': ^1.36.0
    rxjs: ^7.8.2
    tailwind-merge: ^3.4.0
    usehooks-ts: ^3.1.1
